name: CI

on:
  workflow_dispatch:
  push:

jobs:
  build:
    name: Build ${{ matrix.RELEASE }}-${{ matrix.BRANCH }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        BRANCH:
          - edge
          - current
        RELEASE:
          - buster # Ubuntu 20.04 LTS

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          repository: soulteary/armbian-build-s805 --branch=codebase-on-150balbes

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install libmpc-dev
      - name: Build
        run: |
          sudo ./compile.sh \
            BOARD=aml-s805 \
            BRANCH=${{ matrix.BRANCH }} \
            RELEASE=${{ matrix.RELEASE }} \
            KERNEL_CONFIGURE=no \
            KERNEL_ONLY=no \
            BUILD_MINIMAL=yes \
            BUILD_DESKTOP=no \
            EXPERT=yes \
            USE_CCACHE=no \
            COMPRESS_OUTPUTIMAGE=gz,sha,gpg
      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: ${{ matrix.RELEASE }}-${{ matrix.BRANCH }}
          path: output/images/*

  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Download artifacts
        uses: actions/download-artifact@v2
        with:
          path: artifacts/

      - name: Release
        run: |
          time="${{ github.event.head_commit.timestamp }}"
          sha="${GITHUB_SHA:0:8}"
          tag="ci-$(date +'%Y%m%d-%H%M' -d "$time")"
          message="CI $(date +'%Y-%m-%d %H:%M' -d "$time")"
          hub release create $(for a in artifacts/*/*; do echo -a $a; done) -t "$GITHUB_SHA" "$tag" -m "$message"
        env:
          GITHUB_TOKEN: ${{ github.token }}
